from pathlib import Path

path = Path('custom_components/localtuya/climate.py')
text = path.read_text(encoding='utf-8')
marker = '''    @property\n    def target_temperature_step(self):\n        \"\"\"Return the supported step of the active target-temperature mapping.\"\"\"'''
insert = '''    @property\n    def min_temp(self):\n        \"\"\"Return the active mapped minimum target temperature.\"\"\"\n        target_dp = self._active_target_temperature_dp()\n        if target_dp is not None:\n            metadata = self.mapped_numeric_metadata(target_dp)\n            value_range = metadata.get(\"range\")\n            if isinstance(value_range, dict) and \"min\" in value_range:\n                return float(value_range[\"min\"]) * self._target_precision\n        return self._config.get(CONF_TEMP_MIN, DEFAULT_MIN_TEMP)\n\n    @property\n    def max_temp(self):\n        \"\"\"Return the active mapped maximum target temperature.\"\"\"\n        target_dp = self._active_target_temperature_dp()\n        if target_dp is not None:\n            metadata = self.mapped_numeric_metadata(target_dp)\n            value_range = metadata.get(\"range\")\n            if isinstance(value_range, dict) and \"max\" in value_range:\n                return float(value_range[\"max\"]) * self._target_precision\n        return self._config.get(CONF_TEMP_MAX, DEFAULT_MAX_TEMP)\n\n'''
if marker not in text:
    raise SystemExit('target_temperature_step marker missing')
text = text.replace(marker, insert + marker, 1)
path.write_text(text, encoding='utf-8')

test = Path('tests/test_climate_advanced_metadata.py')
test.write_text('''\"\"\"Regression tests for conditional climate mapping metadata.\"\"\"\n\nimport unittest\n\nfrom custom_components.localtuya.const import (\n    CONF_TARGET_PRECISION, CONF_TARGET_TEMPERATURE_DP, CONF_TEMP_MAX, CONF_TEMP_MIN,\n)\nfrom custom_components.localtuya.climate import LocaltuyaClimate\n\n\nclass ClimateAdvancedMetadataTests(unittest.TestCase):\n    @staticmethod\n    def _bare(metadata):\n        climate = object.__new__(LocaltuyaClimate)\n        climate._config = {\n            CONF_TARGET_TEMPERATURE_DP: 2,\n            CONF_TARGET_PRECISION: 0.1,\n            CONF_TEMP_MIN: 5.0,\n            CONF_TEMP_MAX: 40.0,\n        }\n        climate._target_precision = 0.1\n        climate._conf_preset_dp = None\n        climate._conf_preset_set = {}\n        climate.mapped_numeric_metadata = lambda dp: metadata\n        return climate\n\n    def test_conditional_range_updates_ha_min_max(self):\n        climate = self._bare({\"range\": {\"min\": 410, \"max\": 1040}, \"step\": 10})\n        self.assertEqual(climate.min_temp, 41.0)\n        self.assertEqual(climate.max_temp, 104.0)\n        self.assertEqual(climate.target_temperature_step, 1.0)\n\n    def test_static_fallback_remains_unchanged(self):\n        climate = self._bare({})\n        self.assertEqual(climate.min_temp, 5.0)\n        self.assertEqual(climate.max_temp, 40.0)\n\n\nif __name__ == \"__main__\":\n    unittest.main()\n''', encoding='utf-8')
