[tox]
env_list = py314
skipsdist = true

[testenv]
basepython = python3.14
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_test.txt
commands =
    python -m unittest discover -s tests -p "test_*.py" -v
